# __generated__ by Terraform
# Please review these resources and move them into your main configuration files.

# __generated__ by Terraform from "/subscriptions/c785c74c-7bd9-4afa-ac0a-c5d7912e2fda/resourceGroups/site-group-tmpprod/providers/Microsoft.Web/sites/site-drupalservice-tmpprod"
resource "azapi_resource" "drupal_app" {
  name      = local.drupal_app_service_name_effective
  type      = "Microsoft.Web/sites@2024-04-01"
  location  = var.location
  parent_id = "/subscriptions/${var.subscription_id}/resourceGroups/${local.resource_group_name}"
  tags      = local.merged_tags

  body = {
    kind = "app,linux"
    identity = {
      type = "SystemAssigned"
    }
    properties = {
      autoGeneratedDomainNameLabelScope = "TenantReuse"
      clientAffinityEnabled             = false
      clientCertEnabled                 = false
      clientCertExclusionPaths          = null
      clientCertMode                    = "Required"
      containerSize                     = 0
      dailyMemoryTimeQuota              = 0
      dnsConfiguration                  = {}
      enabled                           = true
      endToEndEncryptionEnabled         = false
      hostNameSslStates                 = [] # Custom domains & certs managed separately
      hostNamesDisabled                 = false
      hostingEnvironmentProfile         = null
      httpsOnly                         = var.drupal_https_only
      hyperV                            = false
      ipMode                            = "IPv4"
      isXenon                           = false
      keyVaultReferenceIdentity         = "SystemAssigned"
      managedEnvironmentId              = null
      publicNetworkAccess               = "Enabled"
      redundancyMode                    = "None"
      reserved                          = true
      resourceConfig                    = null
      scmSiteAlsoStopped                = false
      serverFarmId                      = azapi_resource.app_service_plan.id
      siteConfig = {
        alwaysOn                    = true
        linuxFxVersion              = var.drupal_linux_fx_version
        minimumElasticInstanceCount = var.drupal_minimum_elastic_instance_count
        numberOfWorkers             = var.drupal_number_of_workers
        functionAppScaleLimit       = 0
      }
      storageAccountRequired   = false
      virtualNetworkSubnetId   = "${azapi_resource.site-vnet.id}/subnets/${var.subnets["app"].name}"
      vnetBackupRestoreEnabled = false
      vnetContentShareEnabled  = false
      vnetImagePullEnabled     = false
      vnetRouteAllEnabled      = true
      workloadProfileName      = null
    }
  }
  ignore_missing_property   = true
  schema_validation_enabled = true
}
